### ISSUE TITLE
[Feature Request]: Improve image quality even further

### ISSUE THREAD

**Issue by MatthewCrimson** [fibelatti/photo-widget#100]
### Describe your idea

The image quality is improved even more to facilitate further zoom in of large images without it leading to unnecessary artifacts in the showcase.

### Describe how you think it could work

It would require no change on the side of the user

### Additional context

Reasoning for this request:
I have some images that are 4000 by 3000 pixels in which a 300% or even 400% zoom are normally perfectly acceptable in terms of image quality when talking about widget showcase sizes. 

However, currently when using these scaling sizes, substantial quality is lost leading to some blur and grain.

My current workaround is now to crop the image first in another app and then select the cropped file to preserve quality. This is fine however removes much of the purpose of the crop function.

Example, there is another (otherwise inferior) widget app in which full quality is preserved when scaling to the same percentage. Screenshots with comparisons could be provided if deemed necessary.

**Comment by fibelatti** [comment]
@MatthewCrimson thanks for submitting this request, I appreciate the level of detail provided.

I'm gonna tweak the quality of imported images in the next release. For context, any photos added to a widget are copied to the app's internal storage and resized to a max of 1920x1920 to keep storage usage low. That happens before the cropping tool comes up in order to allow re-cropping of the same image, without having to import it again.

However, it's very likely that people who want to add many photos to a widget are using folder syncing instead, so this optimization might not be required.

**Comment by fibelatti** [comment]
@MatthewCrimson this change was included in version 1.14.0, released to Google Play Store today. The update will be available for all users in the upcoming days.

Thanks for suggesting the change!
