### ISSUE TITLE
[Feature Request]: animation as option

### ISSUE THREAD

**Issue by guguss-31** [fibelatti/photo-widget#105]
### Describe your idea

The animation in the app was very great ! 😭 
You can add a setting for animation enable  animation ! (the shapes that moved and turned  )

### Describe how you think it could work

Just add a setting for enable the home animation 😃

**Comment by fibelatti** [comment]
Hi @guguss-31, I'm glad to hear you really liked the home screen shapes! 😄

When reducing app animations as part of another user request, I figured it was better to just remove that one instead of adding a new app preference. That animation was not functional and all others were already very subtle, so a new preference felt unjustified at the time.

I'll consider making it a preference since there might be others like you, who also enjoyed it. Thanks for letting me know!

**Comment by guguss-31** [comment]
Do you think you’ll be able to do something about this? It’s been a month, and I haven’t seen any updates on it.

**Comment by fibelatti** [comment]
@guguss-31 certainly, but it's very low priority. There are two things I'm taking into account:

1. The animation was purely for decoration, not serving any other purpose
2. The app is entirely focused on home screen widgets, configuring and managing them, so I don't expect people to spend a lot of time in-app (which diminishes the value of this type of animation)

Given that, I have given higher priority to shipping features are fixes that are directly related to the app's primary function. I appreciate you caring about it, and I haven't discarded this yet.

**Comment by fibelatti** [comment]
Hi @guguss-31, the home screen shapes are making a comeback in the next app version. They won't be exactly the same as before, but hopefully they'll be nice in their own way. They won't animate by default, but tapping them should do the trick 😄
