### ISSUE TITLE
Bug? "Tap to finish setup" when restoring a nova launcher backup

### ISSUE THREAD

**Issue by Fuoxden** [fibelatti/photo-widget#126]
### Describe the problem

1: Go to nova launcher settings 
2: Click backup & restore
3: Click restore backup
4: Go back to where your widget is on the laucher
5: And done! You will see it says "tap to finish setup"

### Device model

Samsung a54 5g

### Android version

Android 14

### App version

1.18.1

### Additional information

here's a recording of what I described just in case I didn't explain myself the best (I'm not the best at explaining things)

https://github.com/user-attachments/assets/197637dc-ebe7-4f0e-a595-a2eb2b7719fc

I'm wondering if this is a bug or if its just how nova works, basically, when you change config you get the message "Tap to finish setup" It basically forces you to make a new widget, if your not careful you could make a lot of useless widgets if your someone like me where I change my config with a file over and over, You could add a widget selection menu to fix it? Anyways, I hope that helped

**Comment by fibelatti** [comment]
@Fuoxden no worries, you’ve done a great job explaining yourself. This isn’t a bug, nor is it directly related to how Nova works, it’s more about how launchers work in general.

Widgets operate in a separate process from their parent application and are managed by the active launcher. There are two key points to keep in mind:

1. Adding or removing a widget can only be handled by the launcher with direct input from the user (the app can only request the former).
2. The launcher is responsible for assigning system identifiers to widgets.

While I’m not familiar with how Nova works internally, it’s likely that after restoring a backup, the launcher recreates your widgets but assigns them new IDs. This is why you need to reconfigure them, any data tied to the previous IDs no longer matches.

The app doesn’t support automatic widget backups for this reason. Since the widget data is linked to the original system ID, restoring it isn’t straightforward. However, a possible improvement could be enabling an option to import data from an existing widget, similar to how the "Duplicate" function works now.

I’ll need to check the feasibility of implementing this without disrupting the automatic clean-up of "orphaned data" I already have in place.

**Comment by fibelatti** [comment]
Hi @Fuoxden, with version 1.19.0 you should be able to quickly import from a previous widget after restoring a launcher backup.
