### ISSUE TITLE
High resolution pictures are being added incorrectly

### ISSUE THREAD

**Issue by CrPO4** [fibelatti/photo-widget#44]
Hello, thanks for the application, I've been looking for something just like this one for a bit, and it does almost everything I want perfectly except this one thing.

When you add a high-resolution picture - it's being added as a low-res one, and when you scale it you can see that very clearly.
It behaves the same for any type of "picture picking" be it the photo dialog, file manager or gallery apps.

Please, if that is possible, consider fixing this behavior to allow correct import of high resolution pictures (and therefore their cropping) for a high quality widget experince.

As an example, I'm uploading 3 pictures that show the issue.
1.jpg - how it looks when I zoom in via Widget setup page - https://github.com/fibelatti/photo-widget/assets/32630390/27cc47b4-4926-4891-8606-4a6ef21e0f6d
2.jpg - how it looks when I zoom via web browser (or gallery) - https://github.com/fibelatti/photo-widget/assets/32630390/34b94f90-b268-422d-a0c0-bd427d2be18c
3.jpg - source image - https://github.com/fibelatti/photo-widget/assets/32630390/1eb26a83-30ed-4adc-929d-82d95e921ae0

**Comment by fibelatti** [comment]
Hi @CrPO4, thanks for reaching out and for your feedback!

That was done intentionally and I'd like to give you a bit more context. The app leverages the native photo picker which allows you to provide the selected photos to the app without having to grant access to your entire library, making it private by default. In order to keep access to the selected picture, or to allow cropping, the app saves a copy of it to its internal storage, but the copy is a scaled down version which is what you're observing. There's two main reasons for that: 

1. Keeping the internal app storage usage low, as one might select a lot of pictures for a given widget and it wouldn't be desirable to have the app taking a lot of extra space on your phone
2. For the most part the widget will take a small portion of your home screen and you would be seeing a tiny version of the picture anyway, so a high res version felt unnecessary for the majority of the cases

That said, I'm currently working on a settings page for the app which will allow you to customize default behaviors. I'm going to include a toggle which will allow you to enable creating high res widgets, while keeping the current benefits for scenarios where that's not needed.

**Comment by CrPO4** [comment]
@fibelatti 
Thank you for the explanation, that actually makes quite a lot of sense to me now.
Now I'm gonna sit queitly and wait for the release that includes the feature.

**Comment by fibelatti** [comment]
@CrPO4 no problem at all and thanks for understanding. I can't promise that the feature is gonna make it to the very next release, but I'm already working on it and it should become available soon

**Comment by fibelatti** [comment]
Hi @CrPO4, I have an update regarding your request. Unfortunately I won't be able to increase the size of images due to a restriction imposed by Android. Each image added to a widget can use a limited amount of device memory while displayed on screen and as it stands, images around 1000x1000 are very near that limit (or even above that leading to crashes depending on the screen density).

The cropping tool allow you to zoom really far into the image, but hopefully you'll find that the quality isn't as degraded when viewing the widget in your home screen.

**Comment by CrPO4** [comment]
Hi @fibelatti! Thank you for digging into this and letting me know.
I think this issue should be marked as "Won't be done" as it has no reasonable way to implement it.
Thanks so much for trying though, it means a lot.
