### ISSUE TITLE
Unnecessary permissions

### ISSUE THREAD

**Issue by variety754** [fibelatti/photo-widget#48]
Hello! According to exodus privacy your app for some reason has a permission to access network state and prevent phone from sleeping. Why would that be ever needed by a Photo Widget?![Screenshot_2024-04-08-04-05-37-055_org.mozilla.firefox_1.jpg](https://github.com/fibelatti/photo-widget/assets/124847943/8b0eb71d-023e-43d6-96a8-986c85c248b9)

**Comment by fibelatti** [comment]
Hi @variety754, thanks for reaching out! Those permissions are brought in to the app by 1st-party Android library called [WorkManager](https://developer.android.com/reference/androidx/work/WorkManager). That library was being used to enable scheduling jobs to switch photos automatically, but I have updated the mechanism and left it in place to cancel previously scheduled jobs. I'll be removing it fully in the next release.

For further context, although those permissions are brought in they are not used or required for the app to function, and that can be inspected in the source code. `WorkManager` brings them in because it allows you to set constraints to scheduled jobs (e.g. is the device battery low? Is it connected to the internet?), so they are there just in case.

**Comment by variety754** [comment]
Thank you very much for the answer. I'm already using your widget and must say that this is the most functional widget for photos I ever saw and it is really useful for me.
Keep up the work and good luck in the development!

**Comment by fibelatti** [comment]
@variety754 thanks for sharing that with me, it makes me really happy to know when something becomes useful to others!

**Comment by fibelatti** [comment]
@variety754 these permission are being completely removed in version 1.6.0 which will be rolled out in the next couple days
