### ISSUE TITLE
Batch selection 

### ISSUE THREAD

**Issue by JoeInagonY** [fibelatti/photo-widget#55]
Sorry but I just can't get it to work you did reply on play market but I can't figure it out. I can't add folders for example folder1 folder2 I cannot select the folders together and add them but I can go in folder 1 a select the photos 1 at a time in it to add but that's very time consuming when it would be great to select all the folders and it add all photos inside it cause I'm trying to to add up to 35 folders with about 200 photos to each folder so it would be nice to batch select the folders and it add all the photos inside to the widget or allow adding all photos inside folder 1 then hitting back and add folder 2 photos so on long press the folder albums to add just like with images long press and it check them all and then add. You suggested it already works but I cannot get it to I only can open folder one and individually select each picture to add and it's very time consuming then just adding a batch operation I'm not finding any app anywhere to work for me and you are so close oh and selecting all folders in my own gallery app and hitting the share button will not pull up your app to make the widget to share to. I'm using Samsung Galaxy ultra android if that helps please let me know what I'm doing wrong or if what I'm asking for just is not possible because I just cannot figure it out sorry good luck with your app because the play store needs a good one and you about have it for me thanks

**Comment by fibelatti** [comment]
@JoeInagonY even though I've replied to the email I'll post the same reply here in case anybody else has the same issue, this way they may find the answer.

If I understand correctly, some of the things you are trying are not possible because of how the system photo picker works. You have a few options and I'll try to explain them with examples, one by one. I'm also attaching explainer videos as they might help as well. There are two types of widgets:

1. Photo-based

You need to select photos from your device using your preferred photo picker and gallery app. How you get to select photos, including bulk selection is up to those apps. Normally you're able to select multiple photos from a single folder, but not from multiple folders at once. So in this case, if you wish to select photos from multiple folders then you have to open the picker multiple times. I recorded a video showing some of these operations, although you might be familiar with most of them.

2. Folder-based

You need to select a single folder, then all of its photos will be automatically added to the widget, even if you add more photos to that folder later. I also recorded a video demonstrating this.

Also, you mentioned that you're trying to select photos from 35 different folders with roughly 200 photos each for a grand total of 7000 photos. Unfortunately that's currently not possible, even folder-based widgets are currently limited to folders with at most 500 photos, otherwise Android takes a really long time to load them so I'm imposing this limit which I might evaluate increasing in the future but there's little that I can do about the performance since I depend on the system to provide the photos.

---

Demo:

https://github.com/fibelatti/photo-widget/assets/3277516/e2f0496a-fbc4-4b36-af9e-f7f2761337be
