### ISSUE TITLE
Add Google cloud support?

### ISSUE THREAD

**Issue by Dream1975** [fibelatti/photo-widget#68]
Great app, does exactly what I want.

I used the Google photo app to do this, but unfortunately the widget in there only uses photos that are backed up in the cloud and not the ones stored locally. This one is the other way around (what works better for me). 

Most ideally would be if the app would be able to combine these 2 sources (so you can also choose to make a (shuffle) hybrid local folder/google/camera cloud slideshow). Would that be possible to integrate?

**Comment by fibelatti** [comment]
@Dream1975 thanks for your feedback and feature suggestion.

I'm afraid that might not be possible. When using the native picker, Android lets you choose either photos or a local directory. When choosing photos, your preferred picker might offer the ability to choose photos from the cloud (i.e. Google Photos allows that), so that would be the closest thing to what you're looking for, but unfortunately it wouldn't be possible to select a cloud directory as the file structure is "proprietary" meaning that it's not necessarily like a disk file structure.

**Comment by Dream1975** [comment]
That's too bad, but what can't be done can't be done. But thank you for your reply and great app.

One additional question (sorry for bothering you this much) would it be possible to also have the widget as background on the lock screen or doesn't Android allow background widgets there?

**Comment by Dream1975** [comment]
I thought so already as non of the apps offered it on the homescreen (I tried a few but am going to stick with this one). One final question, when you select a folder only that folder is shown. Ideal for me would be if there would be a toggle to also include subfolders. I sort pictures per event in a folder

**Comment by fibelatti** [comment]
@Dream1975 I'm gonna check if there's a way to view the content of subfolders as well, but in the meantime it's already possible to add multiple folders per widget so you should be able to do what you want if you go through the selection multiple times

**Comment by fibelatti** [comment]
@Dream1975 good news: subfolders are supported so I'll make the necessary adjustments and include this change in the next update

**Comment by Dream1975** [comment]
That's great news, thanks a lot

**Comment by fibelatti** [comment]
@Dream1975 the change is included in version 1.9.1 which I started rolling out today, it should become available to 100% of users tomorrow if everything goes smoothly
